  name: "iptables"
  version: "1.1"
  slug: "iptables"
  description: "Add-on to help manage user iptable rules"
  arch: 
    - armhf
    - armv7
    - aarch64
    - amd64 
    - i386
  host_network: true
  privileged: 
    - NET_ADMIN
  init: false
